# Generated by Django 4.2.6 on 2023-10-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("YAC", "AC"),
                            ("NAC", "Non AC"),
                            ("DEL", "Deluxe"),
                            ("KIN", "King"),
                            ("QUE", "Queen"),
                        ],
                        max_length=3,
                    ),
                ),
                ("beds", models.IntegerField()),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
