# Generated by Django 4.2.6 on 2023-10-17 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="name",
            new_name="number",
        ),
    ]
