# Generated by Django 4.2.6 on 2023-10-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0003_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateTimeField(),
        ),
    ]
